## Independence Level Test

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:/ML Internship/chi1__2__lyst1729241145055.csv")
df

     age intervals Experience intervals
0          41 - 50         6 - 10 Years
1          41 - 50         6 - 10 Years
2          31 - 40         6 - 10 Years
3          31 - 40         6 - 10 Years
4          18 - 30         6 - 10 Years
...            ...                  ...
1465       31 - 40        11 - 20 Years
1466       31 - 40         6 - 10 Years
1467       18 - 30         6 - 10 Years
1468       41 - 50        11 - 20 Years
1469       31 - 40         6 - 10 Years

[1470 rows x 2 columns]

In [3]:
df.dtypes

age intervals           object
Experience intervals    object
dtype: object

In [4]:
df["age intervals"].value_counts()

age intervals
31 - 40    619
18 - 30    386
41 - 50    322
51 - 60    143
Name: count, dtype: int64

In [5]:
df["Experience intervals"].value_counts()

Experience intervals
6 - 10 Years     607
11 - 20 Years    340
Upto 5 Years     316
21 - 40 Years    207
Name: count, dtype: int64

In [9]:
ct=pd.crosstab(df["age intervals"],df["Experience intervals"],margins=True)
ct

Experience intervals,11 - 20 Years,21 - 40 Years,6 - 10 Years,Upto 5 Years,All
age intervals,,,,,
18 - 30,22,0,172,192,386
31 - 40,190,20,308,101,619
41 - 50,85,112,110,15,322
51 - 60,43,75,17,8,143
All,340,207,607,316,1470

In [10]:
import scipy

In [12]:
chi2,p,dof,expected=scipy.stats.chi2_contingency(ct)

In [18]:
chi2 #Calcuklated one

np.float64(679.971444973354)

In [14]:
p

np.float64(2.359819766769466e-134)

In [15]:
dof

16

In [17]:
print(expected)

[[  89.27891156   54.35510204  159.38911565   82.97687075  386.        ]
 [ 143.17006803   87.16530612  255.60068027  133.06394558  619.        ]
 [  74.47619048   45.34285714  132.96190476   69.21904762  322.        ]
 [  33.07482993   20.13673469   59.04829932   30.74013605  143.        ]
 [ 340.          207.          607.          316.         1470.        ]]

H0: Age interval has relationship with the experience interval.
H1: Age interval has no relationship with the experience interval.

In [ ]:
chi1=26.296 #Tabulated one

Since calculated value is greater than the tabulated value so we reject the null hypothesis and accept the alternative hypothesis.

## Goodness of Fit:

In [23]:
expected=[30,30,30,30,30]
observed=[10,20,30,40,50]

In [24]:
sum(observed)

150

In [25]:
sum(expected)

150

In [26]:
stats.chisquare(f_obs=observed,f_exp=expected)

Power_divergenceResult(statistic=np.float64(33.333333333333336), pvalue=np.float64(1.020735571764047e-06))

H0: Shopkeeper claim is that he sells 30 chips packet everday is false.
H1: Shopkeeper's claim is true.
Since we do not have enough evidence to find out so we are rejecting the null hypothesis.