# Descriptive Analysis

1. Data set is small in nature.
2. Mean, Median & Mode(Measure of Central Tendency).

## Measure of Central Tendency

In [6]:
import pandas as pd
df=pd.read_csv("D:/Machine Learning/Car_prices.csv")
print(df)

    year       make      model         trim       body transmission  \
0   2006     Toyota      Camry          XLE      Sedan    automatic
1   2014      Honda      Civic           LX      Sedan    automatic
2   2009       Ford      F-150          XLT     Pickup    automatic
3   2012  Chevrolet      Cruze           LT      Sedan    automatic
4   2015        BMW   3 Series         328i      Sedan    automatic
5   2003     Toyota    Corolla           CE      Sedan       manual
6   2011      Honda       CR-V           EX        SUV    automatic
7   2013       Ford    Mustang      Premium      Coupe       manual
8   2010  Chevrolet  Silverado           LT     Pickup    automatic
9   2014        BMW         X5    xDrive35i        SUV    automatic
10  2008     Toyota      Prius         Base  Hatchback    automatic
11  2012      Honda     Accord         EX-L      Sedan    automatic
12  2005       Ford      Focus           SE      Sedan       manual
13  2013  Chevrolet    Equinox           LT        SUV    automatic
14  2011        BMW   3 Series         328i      Coupe    automatic
15  2015     Toyota       RAV4           LE        SUV    automatic
16  2010      Honda      Civic           EX      Sedan    automatic
17  2012       Ford   Explorer          XLT        SUV    automatic
18  2007  Chevrolet     Malibu           LT      Sedan    automatic
19  2013        BMW   5 Series         535i      Sedan    automatic
20  2014     Toyota      Camry           SE      Sedan    automatic
21  2008      Honda     Accord           LX      Coupe       manual
22  2011       Ford      F-150       Lariat     Pickup    automatic
23  2013  Chevrolet      Cruze          Eco      Sedan       manual
24  2012        BMW         X5    xDrive35i        SUV    automatic
25  2015     Toyota    Corolla            S      Sedan    automatic
26  2010      Honda      Pilot         EX-L        SUV    automatic
27  2012       Ford      Focus     Titanium  Hatchback    automatic
28  2014  Chevrolet  Silverado          LTZ     Pickup    automatic
29  2009        BMW   3 Series         328i      Sedan    automatic
30  2011     Toyota      Camry           LE      Sedan    automatic
31  2013      Honda      Civic           Si      Coupe       manual
32  2010       Ford   Explorer  Eddie Bauer        SUV    automatic
33  2012  Chevrolet     Malibu           LT      Sedan    automatic
34  2014        BMW   5 Series         528i      Sedan    automatic
35  2005     Toyota       RAV4         Base        SUV    automatic
36  2015      Honda     Accord        Sport      Sedan    automatic
37  2012       Ford    Mustang         Base      Coupe    automatic
38  2011  Chevrolet    Equinox          LTZ        SUV    automatic
39  2010        BMW   3 Series         335i      Sedan    automatic
40  2013     Toyota      Prius        Three  Hatchback    automatic
41  2014      Honda       CR-V         EX-L        SUV    automatic
42  2007       Ford      F-150          XLT     Pickup    automatic
43  2012  Chevrolet      Cruze           LS      Sedan       manual
44  2013        BMW         X5    xDrive35i        SUV    automatic
45  2006     Toyota    Corolla           LE      Sedan    automatic
46  2011      Honda      Civic           LX      Sedan    automatic
47  2014       Ford      Focus           SE      Sedan    automatic
48  2010  Chevrolet  Silverado           LT     Pickup    automatic
49  2012        BMW   3 Series         328i      Sedan    automatic

                  vin state  condition  odometer   color   interior  \
0   1A2B3C4D5E6F7G8H9    ca        3.2    142000  silver      black
1   9H8G7F6E5D4C3B2A1    tx        4.5     24500   white       gray
2   5K4J3I2H1G0F9E8D7    fl        2.8    115000   black       gray
3   3M4N5O6P7Q8R9S0T1    ny        3.7     68000     red      black
4   7U6V5W4X3Y2Z1A0B9    ca        4.8     12000    blue      black
5   2D3E4F5G6H7I8J9K0    il        2.1    185000    gray       gray
6   8L9M0N1O2P3Q4R5S6    ga        3.9     82000  silver      black
7   1Z2Y3X4W5V6U7T8S9    tx        4.2     35000     red      black
8   0A1B2C3D4E5F6G7H8    mi        3.0    128000   white  dark gray
9   4P5Q6R7S8T9U0V1W2    ny        4.6     21000   black      brown
10  9Z8Y7X6W5V4U3T2S1    ca        3.4    135000    blue       gray
11  3A4B5C6D7E8F9G0H1    pa        4.0     59000    gray      black
12  5M6N7O8P9Q0R1S2T3    oh        1.9    168000  silver       gray
13  7W8X9Y0Z1A2B3C4D5    fl        3.8     71000   black      black
14  2K3L4M5N6O7P8Q9R0    tx        3.6     64000   white        red
15  6U7V8W9X0Y1Z2A3B4    ga        4.7     15000    gray       gray
16  0F9E8D7C6B5A4M3N2    il        3.1     98000    blue       gray
17  4T5U6V7W8X9Y0Z1A2    ca        4.1     54000   white      black
18  8B9C0D1E2F3G4H5I6    mi        2.5    147000  silver       gray
19  1R2S3T4U5V6W7X8Y9    ny        4.3     42000   black      black
20  5G6H7I8J9K0L1M2N3    tx        4.4     28000     red      black
21  9W8X7Y6Z5A4B3C2D1    fl        2.9    122000   black       gray
22  3Q4R5S6T7U8V9W0X1    ca        3.8     93000    gray      black
23  7E8F9G0H1I2J3K4L5    pa        4.0     46000    blue      black
24  1U2V3W4X5Y6Z7A8B9    ga        3.9     61000   white      brown
25  5M6N7O8P9Q0R1S2T3    ny        4.6     18000  silver      black
26  9A0B1C2D3E4F5G6H7    il        3.4    104000   black       gray
27  3K4L5M6N7O8P9Q0R1    tx        3.7     57000  yellow      black
28  7W8X9Y0Z1A2B3C4D5    ca        4.5     31000   black      black
29  1O2P3Q4R5S6T7U8V9    oh        3.0     99000    gray      black
30  5Y6Z7A8B9C0D1E2F3    fl        3.5     88000   white        tan
31  9M0N1O2P3Q4R5S6T7    ca        4.3     39000   black      black
32  3C4D5E6F7G8H9I0J1    ny        3.2    112000    blue        tan
33  7U8V9W0X1Y2Z3A4B5    ga        3.6     73000  silver       gray
34  1I2J3K4L5M6N7O8P9    tx        4.4     26000   white      black
35  5Q6R7S8T9U0V1W2X3    il        2.4    154000   green       gray
36  9E8F9G0H1I2J3K4L5    pa        4.8     14000    gray      black
37  3W4X5Y6Z7A8B9C0D1    ca        3.9     48000   black      black
38  7O8P9Q0R1S2T3U4V5    mi        3.5     89000     red      black
39  1A2B3C4D5E6F7G8H9    fl        3.3     91000    blue       gray
40  5K6L7M8N9O0P1Q2R3    tx        4.1     45000   white       gray
41  9U0V1W2X3Y4Z5A6B7    ny        4.6     22000  silver      black
42  3G4H5I6J7K8L9M0N1    ga        2.7    139000   black       gray
43  7C8D9E0F1G2H3I4J5    oh        3.4     62000   white       gray
44  1M2N3O4P5Q6R7S8T9    ca        4.2     38000   black      black
45  5A6B7C8D9E0F1G2H3    il        2.9    129000  silver       gray
46  9K0L1M2N3O4P5Q6R7    fl        3.6     74000    blue       gray
47  3O4P5Q6R7S8T9U0V1    tx        4.3     29000     red      black
48  7G8H9I0J1K2L3M4N5    pa        3.2    111000    gray      black
49  1Y2Z3A4B5C6D7E8F9    ny        3.8     53000   white      black

                       seller    mmr  sellingprice  \
0   Toyota Financial Services   4500          4300
1            Auto Auction Inc  12800         13100
2           Ford Motor Credit   9200          8900
3            Auto Auction Inc   7400          7600
4      BMW Financial Services  28500         29000
5            Auto Auction Inc   1800          1500
6            Auto Auction Inc  11500         11800
7           Ford Motor Credit  16500         16200
8            Auto Auction Inc  10200          9900
9      BMW Financial Services  39000         39500
10  Toyota Financial Services   5200          5000
11           Auto Auction Inc  11000         11300
12           Auto Auction Inc   1200          1000
13           Auto Auction Inc   9800          9600
14     BMW Financial Services  14200         14000
15  Toyota Financial Services  18500         18900
16           Auto Auction Inc   6800          6600
17          Ford Motor Credit  17200         17500
18           Auto Auction Inc   2900          2700
19     BMW Financial Services  24500         24900
20  Toyota Financial Services  13900         14200
21           Auto Auction Inc   5100          4900
22          Ford Motor Credit  16800         16500
23           Auto Auction Inc   9100          9300
24     BMW Financial Services  22000         21700
25  Toyota Financial Services  14500         14800
26           Auto Auction Inc  12100         11900
27          Ford Motor Credit   8400          8600
28           Auto Auction Inc  29500         30100
29     BMW Financial Services   8900          8600
30  Toyota Financial Services   8200          8400
31           Auto Auction Inc  13400         13700
32          Ford Motor Credit   9500          9200
33           Auto Auction Inc   7100          6900
34     BMW Financial Services  27800         28300
35  Toyota Financial Services   3100          2900
36           Auto Auction Inc  18900         19400
37          Ford Motor Credit  11800         11800
38           Auto Auction Inc  10400         10200
39     BMW Financial Services  11500         11100
40  Toyota Financial Services  12900         13200
41           Auto Auction Inc  17800         18200
42          Ford Motor Credit   6500          6200
43           Auto Auction Inc   6900          6700
44     BMW Financial Services  26500         26800
45  Toyota Financial Services   3400          3200
46           Auto Auction Inc   7900          8100
47          Ford Motor Credit   9800         10100
48           Auto Auction Inc  11800         11500
49     BMW Financial Services  15400         15200

                                   saledate
0   Tue Feb 10 2015 01:30:00 GMT-0800 (PST)
1   Wed Jan 14 2015 04:15:00 GMT-0800 (PST)
2   Thu Dec 18 2014 02:00:00 GMT-0800 (PST)
3   Mon Mar 02 2015 05:30:00 GMT-0800 (PST)
4   Thu Feb 26 2015 01:00:00 GMT-0800 (PST)
5   Fri Jan 09 2015 03:45:00 GMT-0800 (PST)
6   Tue Feb 24 2015 02:15:00 GMT-0800 (PST)
7   Mon Mar 09 2015 04:00:00 GMT-0800 (PST)
8   Wed Jan 21 2015 01:30:00 GMT-0800 (PST)
9   Thu Mar 12 2015 06:00:00 GMT-0800 (PST)
10  Tue Feb 17 2015 01:45:00 GMT-0800 (PST)
11  Mon Jan 26 2015 03:00:00 GMT-0800 (PST)
12  Wed Feb 04 2015 02:30:00 GMT-0800 (PST)
13  Fri Feb 13 2015 05:15:00 GMT-0800 (PST)
14  Tue Mar 03 2015 04:30:00 GMT-0800 (PST)
15  Mon Feb 02 2015 01:15:00 GMT-0800 (PST)
16  Wed Mar 11 2015 02:45:00 GMT-0800 (PST)
17  Thu Jan 22 2015 01:00:00 GMT-0800 (PST)
18  Fri Feb 20 2015 03:30:00 GMT-0800 (PST)
19  Tue Jan 06 2015 05:00:00 GMT-0800 (PST)
20  Wed Feb 25 2015 04:15:00 GMT-0800 (PST)
21  Mon Dec 15 2014 02:15:00 GMT-0800 (PST)
22  Thu Feb 05 2015 01:30:00 GMT-0800 (PST)
23  Fri Jan 30 2015 03:15:00 GMT-0800 (PST)
24  Tue Mar 10 2015 02:00:00 GMT-0800 (PST)
25  Thu Jan 29 2015 06:00:00 GMT-0800 (PST)
26  Wed Feb 11 2015 02:30:00 GMT-0800 (PST)
27  Mon Feb 23 2015 04:45:00 GMT-0800 (PST)
28  Thu Jan 15 2015 01:15:00 GMT-0800 (PST)
29  Wed Mar 04 2015 03:00:00 GMT-0800 (PST)
30  Fri Jan 23 2015 05:30:00 GMT-0800 (PST)
31  Tue Jan 20 2015 01:00:00 GMT-0800 (PST)
32  Thu Feb 12 2015 06:15:00 GMT-0800 (PST)
33  Tue Feb 03 2015 02:15:00 GMT-0800 (PST)
34  Mon Mar 16 2015 04:00:00 GMT-0800 (PST)
35  Wed Jan 07 2015 02:45:00 GMT-0800 (PST)
36  Fri Feb 27 2015 03:30:00 GMT-0800 (PST)
37  Thu Mar 05 2015 01:45:00 GMT-0800 (PST)
38  Wed Feb 18 2015 01:30:00 GMT-0800 (PST)
39  Fri Mar 13 2015 05:00:00 GMT-0800 (PST)
40  Mon Jan 19 2015 04:30:00 GMT-0800 (PST)
41  Thu Feb 19 2015 06:00:00 GMT-0800 (PST)
42  Tue Jan 27 2015 02:00:00 GMT-0800 (PST)
43  Wed Feb 25 2015 03:15:00 GMT-0800 (PST)
44  Thu Feb 12 2015 01:15:00 GMT-0800 (PST)
45  Wed Jan 28 2015 02:30:00 GMT-0800 (PST)
46  Fri Feb 06 2015 05:45:00 GMT-0800 (PST)
47  Mon Feb 02 2015 04:15:00 GMT-0800 (PST)
48  Fri Mar 06 2015 03:00:00 GMT-0800 (PST)
49  Thu Mar 05 2015 06:30:00 GMT-0800 (PST)

In [10]:
pd.DataFrame(df.dtypes, columns=['Data Type'])

             Data Type
year             int64
make            object
model           object
trim            object
body            object
transmission    object
vin             object
state           object
condition      float64
odometer         int64
color           object
interior        object
seller          object
mmr              int64
sellingprice     int64
saledate        object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          50 non-null     int64
 1   make          50 non-null     object
 2   model         50 non-null     object
 3   trim          50 non-null     object
 4   body          50 non-null     object
 5   transmission  50 non-null     object
 6   vin           50 non-null     object
 7   state         50 non-null     object
 8   condition     50 non-null     float64
 9   odometer      50 non-null     int64
 10  color         50 non-null     object
 11  interior      50 non-null     object
 12  seller        50 non-null     object
 13  mmr           50 non-null     int64
 14  sellingprice  50 non-null     int64
 15  saledate      50 non-null     object
dtypes: float64(1), int64(4), object(11)
memory usage: 6.4+ KB

In [12]:
df.describe()

              year  condition       odometer           mmr  sellingprice
count    50.000000  50.000000      50.000000     50.000000     50.000000
mean   2011.120000   3.682000   75210.000000  12672.000000  12700.000000
std       2.904184   0.713911   45368.568865   7893.656456   8084.553173
min    2003.000000   1.900000   12000.000000   1200.000000   1000.000000
25%    2010.000000   3.200000   38250.000000   7525.000000   7725.000000
50%    2012.000000   3.750000   66000.000000  11250.000000  11200.000000
75%    2013.000000   4.275000  109250.000000  16225.000000  15950.000000
max    2015.000000   4.800000  185000.000000  39000.000000  39500.000000

In [13]:
df.describe(include="object")

,make,model,trim,body,transmission,vin,state,color,interior,seller,saledate
count,50,50,50,50,50,50,50,50,50,50,50
unique,5,19,26,5,2,47,9,8,6,4,50
top,Toyota,3 Series,LT,Sedan,automatic,1A2B3C4D5E6F7G8H9,ca,black,black,Auto Auction Inc,Tue Feb 10 2015 01:30:00 GMT-0800 (PST)
freq,10,5,6,24,43,2,9,11,26,22,1

### Measure of Dispersion

In [14]:
range1=df["sellingprice"].max()-df["sellingprice"].min()
print(range1)

38500