In [3]:
import pandas as pd

In [4]:
#from sklearn.datasets import load_boston (but dataset is removed from sklearn)

In [5]:
df=pd.read_csv("D:/ML Internship/load_boston_final_lyst1729240745225.csv")
df

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target_col
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [6]:
df=df.drop("Unnamed: 0",axis=1)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,target_col
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [7]:
#First check whether the model is overfitted or underfitted or not
#Training of model
x=df.iloc[:,1:13]
y=df.iloc[:,-1]

In [8]:
x

,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [9]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: target_col, Length: 506, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=9)

In [11]:
x_train

,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
217,0.0,13.89,0.0,0.550,6.642,85.1,3.4211,5.0,276.0,16.4,392.78,9.69
25,0.0,8.14,0.0,0.538,5.599,85.7,4.4546,4.0,307.0,21.0,303.42,16.51
235,0.0,6.20,0.0,0.507,6.086,61.5,3.6519,8.0,307.0,17.4,376.75,10.88
62,25.0,5.13,0.0,0.453,6.456,67.8,7.2255,8.0,284.0,19.7,396.90,6.73
6,12.5,7.87,0.0,0.524,6.012,66.6,5.5605,5.0,311.0,15.2,395.60,12.43
...,...,...,...,...,...,...,...,...,...,...,...,...
438,0.0,18.10,0.0,0.740,5.935,87.9,1.8206,24.0,666.0,20.2,68.95,34.02
501,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
126,0.0,25.65,0.0,0.581,5.613,95.6,1.7572,2.0,188.0,19.1,359.29,27.26
348,80.0,2.01,0.0,0.435,6.635,29.7,8.3440,4.0,280.0,17.0,390.94,5.99
382,0.0,18.10,0.0,0.700,5.536,100.0,1.5804,24.0,666.0,20.2,396.90,23.60

In [12]:
y_train

217    28.7
25     13.9
235    24.0
62     22.2
6      22.9
       ...
438     8.4
501    22.4
126    15.7
348    24.5
382    11.3
Name: target_col, Length: 354, dtype: float64

In [13]:
x_test

,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
464,0.0,18.10,0.0,0.655,6.209,65.4,2.9634,24.0,666.0,20.2,396.90,13.22
419,0.0,18.10,0.0,0.718,6.824,76.5,1.7940,24.0,666.0,20.2,48.45,22.74
277,40.0,6.41,1.0,0.447,6.826,27.6,4.8628,4.0,254.0,17.6,393.45,4.16
491,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4.0,711.0,20.1,390.11,18.07
337,0.0,5.19,0.0,0.515,5.895,59.6,5.6150,5.0,224.0,20.2,394.81,10.56
...,...,...,...,...,...,...,...,...,...,...,...,...
53,21.0,5.64,0.0,0.439,5.998,21.4,6.8147,4.0,243.0,16.8,396.90,8.43
376,0.0,18.10,0.0,0.671,6.649,93.3,1.3449,24.0,666.0,20.2,363.02,23.24
194,60.0,2.93,0.0,0.401,6.604,18.8,6.2196,1.0,265.0,15.6,376.70,4.38
110,0.0,8.56,0.0,0.520,6.195,54.4,2.7778,5.0,384.0,20.9,393.49,13.00
453,0.0,18.10,0.0,0.713,7.393,99.3,2.4527,24.0,666.0,20.2,375.87,16.74

In [14]:
y_test

464    21.4
419     8.4
277    33.1
491    13.6
337    18.5
       ...
53     23.4
376    13.9
194    29.1
110    21.7
453    17.8
Name: target_col, Length: 152, dtype: float64

In [15]:
#Scaling so that different scales of dataset enteries becomes equal
from sklearn.preprocessing import StandardScaler 
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [16]:
x_train

array([[-0.49769035,  0.36615521, -0.26967994, ..., -0.93684687,
         0.3955109 , -0.45144838],
       [-0.49769035, -0.47155292, -0.26967994, ...,  1.18257719,
        -0.64095962,  0.4925837 ],
       [-0.49769035, -0.75418836, -0.26967994, ..., -0.47610251,
         0.20958183, -0.28672724],
       ...,
       [-0.49769035,  2.07945043, -0.26967994, ...,  0.30716291,
         0.00706643,  1.98061081],
       [ 2.97730737, -1.36462263, -0.26967994, ..., -0.66040025,
         0.37416908, -0.96360655],
       [-0.49769035,  0.97950324, -0.26967994, ...,  0.8139817 ,
         0.44329804,  1.47398949]], shape=(354, 12))

In [17]:
x_test

array([[-0.4656748 ,  1.10674532, -0.27931019, ...,  0.78949089,
         0.44137035,  0.18369117],
       [-0.4656748 ,  1.10674532, -0.27931019, ...,  0.78949089,
        -2.9839543 ,  1.56962616],
       [ 1.20569639, -0.61324736,  3.58024885, ..., -0.42312784,
         0.40745625, -1.13527637],
       ...,
       [ 2.04138199, -1.12527255, -0.27931019, ..., -1.35591149,
         0.24280081, -1.10324846],
       [-0.4656748 , -0.29690995, -0.27931019, ...,  1.11596517,
         0.40784945,  0.15166326],
       [-0.4656748 ,  1.10674532, -0.27931019, ...,  0.78949089,
         0.23464176,  0.69613772]], shape=(152, 12))

In [18]:
from sklearn.linear_model import LinearRegression
lm=LinearRegression()
lm.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred=lm.predict(x_test)

In [20]:
y_pred

array([19.2807889 , 13.74906291, 32.9591278 , 13.49928169, 18.08856021,
       22.7286864 , 33.53144791, 26.71119279, 18.6850353 , 15.91293747,
       16.30290696, 25.8226992 , 14.83960342, 31.36547647, 12.93401529,
       29.6276749 , 17.08133564, 21.08867601, 28.97044163, 16.1671125 ,
       23.81577039,  5.17356216, 22.47186163, 20.08014944, 27.09597728,
       41.96826198, 25.37661216, 19.39614648, 18.29431277, 22.29885151,
       11.82962998, 12.3186103 , 19.59393731, 15.41780341, 20.6965306 ,
       14.41548062, 29.95060979, 16.10480159, 11.7974246 , 38.47997708,
       15.53854206, 21.85935709, 12.15746839, 36.9509247 , 32.97634615,
       19.85927101, 26.98940628, 23.7832698 ,  6.19171785, 25.96092529,
       30.3975491 , 33.74370335, 15.58130117, 25.4919787 ,  7.06876125,
       17.02657145, 18.25211741,  9.55304178, 29.895558  , 15.78373052,
       18.03152697, 27.34674659, 13.9195365 ,  1.0022872 , 30.90391386,
       17.09815543, 16.17254346, 18.59042   , 16.18544398, 21.19923999,
       38.84696978,  4.17204459, 33.47805684, 20.98511046, 17.65228047,
       24.84593157, 21.11226927, 38.24745622, 17.02363525, 17.68555153,
       19.15003701, 29.46538917, 20.90845334, 36.81303944, 12.41089113,
       25.01939677, 25.77544116, 17.51036059, 12.37679212, 14.92930808,
       22.25231329, 16.39724271, 27.02089548, 21.87530056, 17.09868183,
       29.52776793, 23.7289802 , 12.41335967, 19.5808217 , 25.79100448,
       29.58351604, 24.98382135, 26.19049614, 19.8229155 , 30.79379914,
       31.01753426, 15.05653245, 29.38887209, 24.26756926, 29.47218859,
       22.10619575, 14.81450489, 18.85599885, 31.30537034, 22.60273013,
       33.53153964, 20.94364375, 20.67669168, 19.85319137, 19.58557675,
       17.94721679, 23.01882316, 14.60869397, 27.5793149 , 15.72393425,
       16.58615504, 23.77040468, 34.33755226, 34.1102018 , 24.58829596,
       16.36238674, 28.2201257 , 28.68430043, 17.17103049, 25.22912439,
       14.61311913, 31.07945247, 30.69658377, 25.21975356, 18.99446516,
       36.57491883, 21.78436795, 25.24887114, 15.99886245, 24.03635838,
       21.72973   , 41.51258143, 22.66832054, 16.71482694, 29.94992502,
       19.32987895, 21.16990123])

In [21]:
y_test

464    21.4
419     8.4
277    33.1
491    13.6
337    18.5
       ...
53     23.4
376    13.9
194    29.1
110    21.7
453    17.8
Name: target_col, Length: 152, dtype: float64

In [22]:
lm.score(x_train,y_train)

0.7099633678365667

In [23]:
#Performing Cross Validation.
from sklearn.model_selection import cross_val_score

In [31]:
#Mean squared and Mean absolute error for model after cross validation
c_v=cross_val_score(lm,x_train,y_train,scoring="neg_mean_squared_error",cv=10)
print(c_v)
c_v_1=cross_val_score(lm,x_train,y_train,scoring="neg_mean_absolute_error",cv=10)
print(c_v_1)

[-20.24786986 -33.16397231 -39.00857027 -12.03581299 -24.46854872
 -13.52592032 -41.08796705 -40.00437242 -28.00732054 -12.84200506]
[-3.40276499 -3.71019118 -3.77721615 -2.90012014 -3.16623568 -2.7257277
 -4.866665   -4.60400505 -3.64714079 -2.68859732]

In [30]:
#Mean squared and mean absolute error for model before cross validation
from sklearn.metrics import mean_squared_error,mean_absolute_error
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

21.33546418446112
3.189905140347836

In [26]:
c_v.mean()

np.float64(-26.439235953645106)

In [32]:
c_v_1.mean()

np.float64(-3.5488664000615513)

# Ridge Regularisation

In [34]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [38]:
#Hyperparameter tuning for the values of lambda/alpha
ridge_1=Ridge()
parameters={"alpha":[1,2,3,4,5,6,7,10,20,30,40,37]}
ridge_cv=GridSearchCV(ridge_1,parameters,scoring="neg_mean_squared_error",cv=5)

In [39]:
#Training the ridge model
ridge_cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 10, 20, 30, 40, 37]},
             scoring='neg_mean_squared_error')

In [41]:
#Gives the optimal value of alpha
ridge_cv.best_params_

{'alpha': 2}

In [43]:
ridge_pred=ridge_cv.predict(x_test)

In [45]:
#Value of R2 score 
from sklearn.metrics import r2_score
r2_score(ridge_pred,y_test)

0.6330945917832336

In [46]:
#Value of R2 score for normal regeression model
r2_score(y_test,y_pred)

0.7596330201663412

In [47]:
#Regularisation is thus not required as the data is not overfitted

# Lasso Regularisation

In [48]:
from sklearn.linear_model import Lasso

In [50]:
#Hyperparameter tuning for the values of lambda/alpha
lasso_1=Lasso()
parameters={"alpha":[1,2,3,4,5,6,7,10,20,30,40,37]}
lasso_cv=GridSearchCV(lasso_1,parameters,scoring="neg_mean_squared_error",cv=5)

In [51]:
#Training the lasso model
lasso_cv.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 2, 3, 4, 5, 6, 7, 10, 20, 30, 40, 37]},
             scoring='neg_mean_squared_error')

In [52]:
lasso_pred=lasso_cv.predict(x_test)

In [53]:
r2_score(y_test,lasso_pred)

0.6578269959685433