In [1]:
import pandas as pd

In [25]:
df=pd.read_csv("D:/ML Internship/Titanic-Dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [26]:
df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked"],axis=1,inplace=True)
df

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [17]:
#Picking the value of x and y
x=df.drop("Survived",axis=1)
y=df["Survived"]

In [18]:
x

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [19]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [20]:
#Encoding of Categorical data
dummy=pd.get_dummies(x["Sex"],dtype="int")
dummy

     female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [21]:
#Concatenating the dummy variables
x=pd.concat([x,dummy],axis=1)

In [22]:
x

     Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [27]:
x.drop(["Sex"],axis=1,inplace=True)
x

     Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [29]:
x.dtypes

Pclass      int64
Age       float64
Fare      float64
female      int64
male        int64
dtype: object

In [34]:
#Checking and filling of null values
x.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [32]:
x["Age"]=x["Age"].fillna(x["Age"].median())

In [33]:
x.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [35]:
#Splitting of dataset into Training set and Test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=7)

In [36]:
x_train

     Pclass   Age      Fare  female  male
192       3  19.0    7.8542       1     0
191       2  19.0   13.0000       0     1
714       2  52.0   13.0000       0     1
532       3  17.0    7.2292       0     1
132       3  47.0   14.5000       1     0
..      ...   ...       ...     ...   ...
579       3  32.0    7.9250       0     1
502       3  28.0    7.6292       1     0
537       1  30.0  106.4250       1     0
196       3  28.0    7.7500       0     1
175       3  18.0    7.8542       0     1

[623 rows x 5 columns]

In [37]:
y_train

192    1
191    0
714    0
532    0
132    0
      ..
579    1
502    0
537    1
196    0
175    0
Name: Survived, Length: 623, dtype: int64

In [38]:
x_test

     Pclass   Age     Fare  female  male
725       3  20.0   8.6625       0     1
861       2  21.0  11.5000       0     1
528       3  39.0   7.9250       0     1
46        3  28.0  15.5000       0     1
627       1  21.0  77.9583       1     0
..      ...   ...      ...     ...   ...
347       3  28.0  16.1000       1     0
218       1  32.0  76.2917       1     0
239       2  33.0  12.2750       0     1
491       3  21.0   7.2500       0     1
872       1  33.0   5.0000       0     1

[268 rows x 5 columns]

In [39]:
y_test

725    0
861    0
528    0
46     0
627    1
      ..
347    1
218    1
239    0
491    0
872    0
Name: Survived, Length: 268, dtype: int64

In [44]:
#Application of model
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [41]:
y_pred=model.predict(x_test)

In [42]:
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0])

In [43]:
y_test

725    0
861    0
528    0
46     0
627    1
      ..
347    1
218    1
239    0
491    0
872    0
Name: Survived, Length: 268, dtype: int64

In [48]:
#Classification report
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.83      0.80       156
           1       0.73      0.64      0.69       112

    accuracy                           0.75       268
   macro avg       0.75      0.74      0.74       268
weighted avg       0.75      0.75      0.75       268

In [49]:
#Confusion matrix
confusion_matrix(y_test,y_pred)

array([[130,  26],
       [ 40,  72]])

In [52]:
#The probability behind the x features
pd.options.display.float_format="{:,.1f}".format
x=model.predict_proba(x_test[:10])

In [51]:
x

array([[0.99151615, 0.00848385],
       [0.98297732, 0.01702268],
       [0.99358042, 0.00641958],
       [0.99297895, 0.00702105],
       [0.00173503, 0.99826497],
       [0.02296986, 0.97703014],
       [0.99321441, 0.00678559],
       [0.99305847, 0.00694153],
       [0.98533414, 0.01466586],
       [0.00162938, 0.99837062]])