# Absolute Maximum Scaling

In [1]:
import pandas as pd

In [13]:
df=pd.DataFrame({"LoArea":[8450,9600,11250,9550,14260],"MSSubClass":[60,20,60,70,60]})
df

   LoArea  MSSubClass
0    8450          60
1    9600          20
2   11250          60
3    9550          70
4   14260          60

In [14]:
#Finding the absolute value
import numpy as np
max_val=np.max(np.abs(df))
max_val

14260

In [15]:
print((df-max_val)/max_val)

     LoArea  MSSubClass
0 -0.407433   -0.995792
1 -0.326788   -0.998597
2 -0.211080   -0.995792
3 -0.330295   -0.995091
4  0.000000   -0.995792

# Min-Max Scaling

In [16]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaled_data=scaler.fit_transform(df)
scaled_df=pd.DataFrame(scaled_data,columns=df.columns)
scaled_df

     LoArea  MSSubClass
0  0.000000         0.8
1  0.197935         0.0
2  0.481928         0.8
3  0.189329         1.0
4  1.000000         0.8

# Normalization

In [19]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer()
scaled_entry=scaler.fit_transform(df)
scaled_df=pd.DataFrame(scaled_entry,columns=df.columns)
scaled_df

     LoArea  MSSubClass
0  0.999975    0.007100
1  0.999998    0.002083
2  0.999986    0.005333
3  0.999973    0.007330
4  0.999991    0.004208

# Standardization

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(df)

array([[-1.07161162,  0.3441236 ],
       [-0.50422978, -1.95003374],
       [ 0.30983982,  0.3441236 ],
       [-0.52889855,  0.91766294],
       [ 1.79490013,  0.3441236 ]])

# Robust Scaling

In [24]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
scaler.fit_transform(df)

array([[-6.76470588e-01,  0.00000000e+00],
       [ 0.00000000e+00, -4.00000000e+01],
       [ 9.70588235e-01,  0.00000000e+00],
       [-2.94117647e-02,  1.00000000e+01],
       [ 2.74117647e+00,  0.00000000e+00]])